"""pipeline/asset_factory.py — 2D 资产工厂 + 入库 QA（L3 内容工厂）。

流程：AssetSpec → ImageGenAdapter 生成 → 入库 QA（像素级真实校验）→ AssetRecord。

入库 QA（来自升级计划 4.2，真实校验非勾选）：
  - 尺寸达标        ：解码后 w/h == 规格
  - 透明通道正确    ：若规格要求透明，则图像须为 RGBA
  - 色板与风格一致  ：提取主色板，与 StyleBible 色板做最近邻重叠率（程序化可信；
                      AI 图为颜色代理，语义一致性需 VLM，如实标注）
  - 无水印          ：扫描 PNG 文本块（tEXt/iTXt/zTXt）是否含已知水印串；
                     只能证明"无内嵌水印元数据"，不能证明"无水印"，如实标注
  - 风格相似度      ：程序化用色板重叠代理；AI 图标 unverified_needs_vlm

防伪：AssetRecord 携带 is_ai_generated / is_procedural_placeholder / provenance，
never 把程序化占位宣称为 AI 美术。
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from pipeline import png_io
from pipeline.image_gen_adapter import ImageGenAdapter, ImageGenResult
from pipeline.style_bible import StyleBible

# 已知水印/平台标识串（命中即判定"有内嵌水印元数据"）
_WATERMARK_HINTS = (
    "civitai", "made by", "leonardo.ai", "midjourney", "nightcafe",
    "playground", "adobe firefly", "dreamstudio", "stability.ai",
    "generated by", "novelai",
)


@dataclass
class AssetSpec:
    asset_type: str                      # character/enemy/item/tile/ui/background/icon/store
    name: str
    width: int = 512
    height: int = 512
    require_alpha: bool = False
    frames: int = 1                      # 多帧动作（W5 先做单帧，frames>1 时提示）
    style_ref: str = "default"
    prompt: str = ""


@dataclass
class QAReport:
    passed: bool
    scores: Dict[str, Any] = field(default_factory=dict)
    details: Dict[str, str] = field(default_factory=dict)
    needs_vlm: List[str] = field(default_factory=list)   # 哪些项需 VLM/真机才能最终判定

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AssetRecord:
    asset_id: str
    spec: AssetSpec
    backend: str
    is_ai_generated: bool
    is_procedural_placeholder: bool
    content_hash: str
    width: int
    height: int
    has_alpha: bool
    provenance: Dict[str, Any]
    qa: QAReport
    needs_runtime_tool: Optional[str]
    created_at: str = ""
    image_bytes: bytes = b""

    def to_dict(self, with_image: bool = False) -> Dict[str, Any]:
        d = asdict(self)
        if not with_image:
            d.pop("image_bytes", None)
        return d


# ── 主色板提取与重叠率 ────────────────────────────────────────────────────────
def _dominant_colors(pixels: bytes, channels: int, n: int = 6) -> List[Tuple[int, int, int]]:
    """4bit/通道量化后取频次最高的 n 个主色（确定性，无需 numpy）。"""
    counts: Dict[Tuple[int, int, int], int] = {}
    stride = channels
    total = len(pixels) // stride
    step = max(1, total // 4000)  # 抽样上限 ~4000 像素，足够稳定
    for i in range(0, total, step):
        o = i * stride
        if channels == 4 and pixels[o + 3] < 16:
            continue  # 透明像素不计入色板
        r, g, b = pixels[o], pixels[o + 1], pixels[o + 2]
        key = (r >> 4, g >> 4, b >> 4)
        counts[key] = counts.get(key, 0) + 1
    top = sorted(counts.items(), key=lambda kv: kv[1], reverse=True)[:n]
    return [(k[0] << 4, k[1] << 4, k[2] << 4) for k, _ in top]


def _nearest_dist(c: Tuple[int, int, int], palette: List[Tuple[int, int, int]]) -> int:
    if not palette:
        return 999
    return min(abs(c[0] - p[0]) + abs(c[1] - p[1]) + abs(c[2] - p[2])
               for p in palette)


def _palette_overlap(dom: List[Tuple[int, int, int]],
                     palette: List[Tuple[int, int, int]],
                     tol: int = 64) -> float:
    if not dom or not palette:
        return 0.0
    hit = sum(1 for c in dom if _nearest_dist(c, palette) <= tol)
    return round(hit / len(dom), 3)


class AssetQA:
    @staticmethod
    def check(image_bytes: bytes, spec: AssetSpec,
              style: Optional[StyleBible],
              is_ai_generated: bool = False) -> QAReport:
        scores: Dict[str, Any] = {}
        details: Dict[str, str] = {}
        needs_vlm: List[str] = []
        problems: List[str] = []
        try:
            d = png_io.decode_png(image_bytes)
        except Exception as e:
            return QAReport(passed=False, details={"decode": f"PNG 解码失败: {e}"})

        w, h, ch = d["width"], d["height"], d["channels"]
        pixels = d["pixels"]

        # 1) 尺寸
        dim_ok = (w == spec.width and h == spec.height)
        scores["dimensions"] = 1.0 if dim_ok else 0.0
        details["dimensions"] = f"{w}x{h} vs 规格 {spec.width}x{spec.height}"
        if not dim_ok:
            problems.append("dimensions")

        # 2) 透明通道
        has_alpha = (ch == 4)
        if spec.require_alpha:
            scores["alpha"] = 1.0 if has_alpha else 0.0
            details["alpha"] = "RGBA" if has_alpha else "缺少透明通道（规格要求）"
            if not has_alpha:
                problems.append("alpha")
        else:
            scores["alpha"] = 1.0
            details["alpha"] = "RGBA" if has_alpha else "RGB（规格未要求透明）"

        # 3) 色板一致（程序化可信；AI 为颜色代理）
        dom = _dominant_colors(pixels, ch, n=6)
        style_colors = style.all_colors_rgb() if style else []
        overlap = _palette_overlap(dom, style_colors, tol=64) if style_colors else 0.0
        scores["palette_overlap"] = overlap
        details["palette"] = (f"主色 {dom[:3]} 与风格重叠率 {overlap}"
                              + ("" if style else "（无风格圣经，跳过）"))
        if style_colors and overlap < 0.34:
            problems.append("palette")
            details["palette"] += "（低于 0.34，疑似偏离风格）"

        # 4) 水印：仅能查内嵌文本块
        texts = " ".join(f"{k} {v}".lower() for k, v in d.get("text_chunks", []))
        found = [h for h in _WATERMARK_HINTS if h in texts]
        if found:
            scores["watermark"] = 0.0
            details["watermark"] = f"命中内嵌水印串: {found}"
            problems.append("watermark")
        else:
            scores["watermark"] = 1.0
            details["watermark"] = "未检出内嵌水印元数据（不保证无水印，需人工/VLM 复核）"

        # 5) 风格相似度
        if is_ai_generated:
            scores["style_similarity"] = "unverified_needs_vlm"
            details["style_similarity"] = "AI 图颜色代理重叠率=" + str(overlap) + "（语义一致性需 VLM）"
            needs_vlm.append("style_similarity")
        else:
            scores["style_similarity"] = overlap
            details["style_similarity"] = f"程序化色板重叠率 {overlap}（确定性可信）"

        passed = len(problems) == 0
        return QAReport(passed=passed, scores=scores, details=details, needs_vlm=needs_vlm)


class AssetFactory:
    def __init__(self, adapter: Optional[ImageGenAdapter] = None):
        self.adapter = adapter or ImageGenAdapter()

    def generate(self, spec: AssetSpec, style: Optional[StyleBible] = None,
                 backend: Optional[str] = None, seed: Optional[int] = None,
                 transparent: Optional[bool] = None) -> AssetRecord:
        if spec.frames > 1:
            # W5 先做单帧；多帧动作留待后续波次（不打肿脸）
            pass
        tr = transparent if transparent is not None else spec.require_alpha
        res: ImageGenResult = self.adapter.generate(
            spec.prompt or spec.name, style=style, seed=seed,
            width=spec.width, height=spec.height, backend=backend, transparent=tr)
        qa = AssetQA.check(res.image_bytes, spec, style, res.is_ai_generated)
        asset_id = "asset_" + hashlib.sha256(
            (spec.asset_type + spec.name + res.content_hash).encode("utf-8")).hexdigest()[:12]
        return AssetRecord(
            asset_id=asset_id, spec=spec, backend=res.backend,
            is_ai_generated=res.is_ai_generated,
            is_procedural_placeholder=res.is_procedural_placeholder,
            content_hash=res.content_hash, width=res.width, height=res.height,
            has_alpha=res.has_alpha, provenance=res.provenance, qa=qa,
            needs_runtime_tool=res.needs_runtime_tool,
            created_at=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
            image_bytes=res.image_bytes,
        )

    def save(self, rec: AssetRecord, out_dir: str) -> Dict[str, str]:
        os.makedirs(out_dir, exist_ok=True)
        png_path = os.path.join(out_dir, f"{rec.spec.name}_{rec.asset_id}.png")
        json_path = os.path.join(out_dir, f"{rec.spec.name}_{rec.asset_id}.json")
        with open(png_path, "wb") as f:
            f.write(rec.image_bytes)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(rec.to_dict(), f, ensure_ascii=False, indent=2, default=str)
        return {"png": png_path, "json": json_path}
