#!/usr/bin/env python3
"""
godot_full_engine.py: Agent 核心 Godot 4 原生工业工程全套装配中枢
彻底告别单文件 HTML 拼凑方块的伪 3D，让 Agent 拥有自主生成分层多预制体、标准 TSCN、
纯正 GDScript 4 原生物理 (move_and_slide)、PBR 光照环境与绝对刚性空气墙的完整能力。
"""
from pathlib import Path
from typing import Dict, Any
from knowledge.godot_engine_specs import GodotEngineSpecsKnowledge

class GodotFullEngine:

    @staticmethod
    def assemble_full_godot_project(title: str, genre: str, target_dir: Path) -> Dict[str, Path]:
        """全自动装配标准 Godot 4 3D 工业游戏工程"""
        target_dir.mkdir(parents=True, exist_ok=True)
        scenes_dir = target_dir / "scenes"
        scripts_dir = target_dir / "scripts"
        scenes_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir.mkdir(parents=True, exist_ok=True)

        generated_files = {}

        # -------------------------------------------------------------
        # 1. project.godot (带标准输入映射、32位物理层与 Forward+ 渲染管线)
        # -------------------------------------------------------------
        proj_godot = f"""; Engine configuration file for Godot 4.x
; Generated automatically by Game Dev Agent Studios (Native Godot 4 Pipeline)

config_version=5

[application]

config/name="{title}"
config/description="Commercial 3D Game Project generated by Game Dev Agent Studios"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/size/mode=0
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[layer_names]

3d_physics/layer_1="World_Static"
3d_physics/layer_2="Player"
3d_physics/layer_3="Enemies"
3d_physics/layer_4="Projectiles"

[physics]

3d/default_gravity=9.8

[rendering]

renderer/rendering_method="forward_plus"
anti_aliasing/quality/msaa_3d=2
lights_and_shadows/directional_shadow/soft_shadow_filter_quality=3

{GodotEngineSpecsKnowledge.STANDARD_INPUT_MAP_SECTION}
"""
        proj_file = target_dir / "project.godot"
        proj_file.write_text(proj_godot, encoding="utf-8")
        generated_files["project"] = proj_file

        # -------------------------------------------------------------
        # 2. scripts/player.gd (纯正 GDScript 4: 胶囊体、重力、move_and_slide)
        # -------------------------------------------------------------
        player_gd_file = scripts_dir / "player.gd"
        player_gd_file.write_text(GodotEngineSpecsKnowledge.CHARACTER_BODY_3D_STANDARD_GD, encoding="utf-8")
        generated_files["script_player"] = player_gd_file

        # -------------------------------------------------------------
        # 3. scripts/enemy.gd (3D 敌人追击与受击状态机)
        # -------------------------------------------------------------
        enemy_gd = """extends CharacterBody3D

# 3D 敌军特战 AI - CharacterBody3D 状态机
@export var speed: float = 3.5
@export var max_hp: float = 100.0
var hp: float = 100.0
var target: Node3D = null

func _ready() -> void:
	hp = max_hp
	# 自动寻找场景中的玩家实体
	target = get_tree().get_first_node_in_group("player")

func _physics_process(delta: float) -> void:
	if not is_on_floor():
		velocity.y -= 9.8 * delta
		
	if target and is_instance_valid(target):
		var dir = (target.global_position - global_position).normalized()
		dir.y = 0 # 锁定水平面移动
		velocity.x = dir.x * speed
		velocity.z = dir.z * speed
		if dir.length() > 0.1:
			look_at(global_position + dir, Vector3.UP)
	else:
		velocity.x = 0
		velocity.z = 0

	move_and_slide()

func take_damage(amount: float) -> void:
	hp -= amount
	if hp <= 0:
		queue_free()
"""
        enemy_gd_file = scripts_dir / "enemy.gd"
        enemy_gd_file.write_text(enemy_gd, encoding="utf-8")
        generated_files["script_enemy"] = enemy_gd_file

        # -------------------------------------------------------------
        # 4. scenes/player.tscn (具备胶囊体碰撞、弹簧臂相机与战甲实体)
        # -------------------------------------------------------------
        player_tscn = """[gd_scene load_steps=5 format=3 uid="uid://player001gd4"]

[ext_resource type="Script" path="res://scripts/player.gd" id="1_player"]

[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_p1"]
radius = 0.4
height = 1.8

[sub_resource type="CapsuleMesh" id="CapsuleMesh_p2"]
radius = 0.4
height = 1.8

[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_p3"]
albedo_color = Color(0.12, 0.45, 0.95, 1)
metallic = 0.5
roughness = 0.3

[node name="Player" type="CharacterBody3D" groups=["player"]]
collision_layer = 2
collision_mask = 13
script = ExtResource("1_player")

[node name="CollisionShape3D" type="CollisionShape3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
shape = SubResource("CapsuleShape3D_p1")

[node name="ArmorMesh" type="MeshInstance3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
mesh = SubResource("CapsuleMesh_p2")
surface_material_override/0 = SubResource("StandardMaterial3D_p3")

[node name="CameraPivot" type="Node3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.6, 0)

[node name="Camera3D" type="Camera3D" parent="CameraPivot"]
current = true
fov = 75.0
"""
        player_tscn_file = scenes_dir / "player.tscn"
        player_tscn_file.write_text(player_tscn, encoding="utf-8")
        generated_files["scene_player"] = player_tscn_file

        # -------------------------------------------------------------
        # 5. scenes/enemy.tscn (敌军 CharacterBody3D 预制体)
        # -------------------------------------------------------------
        enemy_tscn = """[gd_scene load_steps=5 format=3 uid="uid://enemy001gd4"]

[ext_resource type="Script" path="res://scripts/enemy.gd" id="1_enemy"]

[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_e1"]
radius = 0.4
height = 1.8

[sub_resource type="CapsuleMesh" id="CapsuleMesh_e2"]
radius = 0.4
height = 1.8

[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_e3"]
albedo_color = Color(0.95, 0.15, 0.25, 1)
metallic = 0.6
roughness = 0.4

[node name="Enemy" type="CharacterBody3D"]
collision_layer = 4
collision_mask = 11
script = ExtResource("1_enemy")

[node name="CollisionShape3D" type="CollisionShape3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
shape = SubResource("CapsuleShape3D_e1")

[node name="MeshInstance3D" type="MeshInstance3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
mesh = SubResource("CapsuleMesh_e2")
surface_material_override/0 = SubResource("StandardMaterial3D_e3")
"""
        enemy_tscn_file = scenes_dir / "enemy.tscn"
        enemy_tscn_file.write_text(enemy_tscn, encoding="utf-8")
        generated_files["scene_enemy"] = enemy_tscn_file

        # -------------------------------------------------------------
        # 6. scenes/main.tscn (主关卡: WorldEnvironment光影 + 封闭刚性空气墙)
        # -------------------------------------------------------------
        main_tscn = f"""[gd_scene load_steps=10 format=3 uid="uid://maingd4stage001"]

[ext_resource type="PackedScene" path="res://scenes/player.tscn" id="1_player"]
[ext_resource type="PackedScene" path="res://scenes/enemy.tscn" id="2_enemy"]

[sub_resource type="ProceduralSkyMaterial" id="ProceduralSkyMaterial_m1"]
sky_top_color = Color(0.08, 0.12, 0.22, 1)
sky_horizon_color = Color(0.25, 0.35, 0.55, 1)
ground_bottom_color = Color(0.05, 0.08, 0.12, 1)

[sub_resource type="Sky" id="Sky_m2"]
sky_material = SubResource("ProceduralSkyMaterial_m1")

[sub_resource type="Environment" id="Environment_m3"]
background_mode = 2
sky = SubResource("Sky_m2")
tonemap_mode = 3
glow_enabled = true
glow_intensity = 0.4
glow_bloom = 0.25

[sub_resource type="BoxShape3D" id="BoxShape3D_floor"]
size = Vector3(100, 1, 100)

[sub_resource type="BoxMesh" id="BoxMesh_floor"]
size = Vector3(100, 1, 100)

[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_floor"]
albedo_color = Color(0.12, 0.16, 0.24, 1)
metallic = 0.2
roughness = 0.8

[sub_resource type="BoxShape3D" id="BoxShape3D_wall"]
size = Vector3(100, 20, 2)

[node name="Main" type="Node3D"]

[node name="WorldEnvironment" type="WorldEnvironment" parent="."]
environment = SubResource("Environment_m3")

[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]
transform = Transform3D(0.866, -0.25, 0.433, 0, 0.866, 0.5, -0.5, -0.433, 0.75, 20, 30, 20)
light_color = Color(0.9, 0.95, 1, 1)
light_energy = 1.3
shadow_enabled = true

[node name="Floor" type="StaticBody3D" parent="."]
collision_mask = 0

[node name="CollisionShape3D" type="CollisionShape3D" parent="Floor"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)
shape = SubResource("BoxShape3D_floor")

[node name="MeshInstance3D" type="MeshInstance3D" parent="Floor"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)
mesh = SubResource("BoxMesh_floor")
surface_material_override/0 = SubResource("StandardMaterial3D_floor")

[node name="PerimeterWalls" type="StaticBody3D" parent="."]
collision_mask = 0

[node name="WallNorth" type="CollisionShape3D" parent="PerimeterWalls"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 10, -50)
shape = SubResource("BoxShape3D_wall")

[node name="WallSouth" type="CollisionShape3D" parent="PerimeterWalls"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 10, 50)
shape = SubResource("BoxShape3D_wall")

[node name="WallWest" type="CollisionShape3D" parent="PerimeterWalls"]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, -50, 10, 0)
shape = SubResource("BoxShape3D_wall")

[node name="WallEast" type="CollisionShape3D" parent="PerimeterWalls"]
transform = Transform3D(0, 0, 1, 0, 1, 0, -1, 0, 0, 50, 10, 0)
shape = SubResource("BoxShape3D_wall")

[node name="Player" parent="." instance=ExtResource("1_player")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0)

[node name="Enemy1" parent="." instance=ExtResource("2_enemy")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 15, 1, -12)

[node name="Enemy2" parent="." instance=ExtResource("2_enemy")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -18, 1, 15)
"""
        main_tscn_file = scenes_dir / "main.tscn"
        main_tscn_file.write_text(main_tscn, encoding="utf-8")
        generated_files["scene_main"] = main_tscn_file

        # -------------------------------------------------------------
        # 7. export_presets.cfg (官方跨端发行导出配置)
        # -------------------------------------------------------------
        presets_cfg = """[preset.0]

name="Windows Desktop"
platform="Windows Desktop"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="./build/game.exe"

[preset.0.options]

custom_template/debug=""
custom_template/release=""
binary_format/embed_pck=true
"""
        (target_dir / "export_presets.cfg").write_text(presets_cfg, encoding="utf-8")

        # -------------------------------------------------------------
        # 8. run_godot.bat (Windows 桌面一键双击运行脚本)
        # -------------------------------------------------------------
        bat_content = f"""@echo off
chcp 65001 >nul
echo =================================================================
echo   🎮 启动 Godot 4 原生工业游戏工程: {title}
echo =================================================================

where godot >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo [启动中] 正在拉起 Godot 4 独立桌面 3D 视口...
    godot --path "%~dp0."
    goto end
)

where godot4 >nul 2>&1
if %ERRORLEVEL% equ 0 (
    echo [启动中] 正在拉起 Godot 4 独立桌面 3D 视口...
    godot4 --path "%~dp0."
    goto end
)

echo [提示] 未在系统 PATH 中检测到 godot.exe。
echo 请打开 Godot Engine 4.x 编辑器，点击「导入 (Import)」
echo 选择本目录下的 project.godot 即可直接体验完整 3D 游戏工程！
pause

:end
"""
        (target_dir / "run_godot.bat").write_text(bat_content, encoding="utf-8")

        return generated_files
