#!/usr/bin/env python3
"""
godot_engine_specs.py: Godot 4 引擎规范、场景树标准与 Shader 模版知识库
为架构师与技术工程部提供标准场景组织、32位物理掩码与着色器模板。
"""
from typing import Dict, List, Any

class GodotEngineSpecsKnowledge:

    # 1. 32 位物理层分配标准规范 (Physics Layers & Collision Masks)
    PHYSICS_LAYERS_STANDARD = {
        1: {"name": "World_Static", "description": "静态地形、不可破坏墙体、地面"},
        2: {"name": "Player", "description": "玩家主实体 Hitbox"},
        3: {"name": "Enemies", "description": "所有敌方怪物实体"},
        4: {"name": "Player_Projectiles", "description": "玩家发射的子弹与法术"},
        5: {"name": "Enemy_Projectiles", "description": "敌方发射的子弹与伤害弹幕"},
        6: {"name": "Pickups_Loot", "description": "金币、道具、掉落物触发区 (Area2D/3D)"},
        7: {"name": "Hazards_Traps", "description": "地刺、岩浆等环境陷阱"},
        8: {"name": "Interactables", "description": "宝箱、NPC、传送门交互触发区"}
    }

    # 2. 标准场景树组织规范 (Scene Tree Architecture)
    SCENE_TREE_STANDARD = """
    Main (Node2D / Node3D) [脚本: main.gd]
    ├── Environment (TileMap / WorldEnvironment)
    ├── Entities
    │   ├── Player (CharacterBody2D / 3D) [CollisionLayer: 2, Mask: 1, 5, 6, 7]
    │   └── Enemies (Node)
    ├── Projectiles (Node - 对象池托管)
    ├── Camera (Camera2D / Camera3D)
    └── UI_Layer (CanvasLayer)
        ├── HUD (Control)
        └── PauseMenu (Control)
    """

    # 3. 经典受击高亮闪白 Shader (Hit Flash Shader - Godot 4 CanvasItem)
    HIT_FLASH_SHADER_GD = """shader_type canvas_item;

uniform bool flash_active = false;
uniform vec4 flash_color : source_color = vec4(1.0, 1.0, 1.0, 1.0);

void fragment() {
    vec4 texture_color = texture(TEXTURE, UV);
    if (flash_active) {
        COLOR = vec4(flash_color.rgb, texture_color.a);
    } else {
        COLOR = texture_color;
    }
}
"""

    # 4. 3D PBR 发光轮廓 Shader (Fresnel Rim Light - Godot 4 Spatial Shader)
    RIM_LIGHT_SHADER_GD = """shader_type spatial;

uniform vec4 base_color : source_color = vec4(0.2, 0.4, 0.8, 1.0);
uniform vec4 rim_color : source_color = vec4(0.0, 0.9, 1.0, 1.0);
uniform float rim_power = 3.0;

void fragment() {
    ALBEDO = base_color.rgb;
    float fresnel = pow(1.0 - clamp(dot(NORMAL, VIEW), 0.0, 1.0), rim_power);
    EMISSION = rim_color.rgb * fresnel * 2.0;
}
"""

    # 5. Godot 4 原生 CharacterBody3D 工业级物理移动规范 (自带重力、吸附与防穿模)
    CHARACTER_BODY_3D_STANDARD_GD = """extends CharacterBody3D

# 工业级 CharacterBody3D 移动状态机 (带重力、跳跃与鼠标瞄准)
# Generated by Game Dev Agent Studios

@export var speed: float = 7.0
@export var jump_velocity: float = 4.5
@export var mouse_sensitivity: float = 0.002

@onready var camera_pivot: Node3D = $CameraPivot
@onready var camera: Camera3D = $CameraPivot/Camera3D

var gravity: float = ProjectSettings.get_setting("physics/3d/default_gravity")

func _ready() -> void:
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion and Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
		rotate_y(-event.relative.x * mouse_sensitivity)
		camera_pivot.rotate_x(-event.relative.y * mouse_sensitivity)
		camera_pivot.rotation.x = clamp(camera_pivot.rotation.x, -PI/2.4, PI/2.4)
	
	if event.is_action_pressed("ui_cancel"):
		if Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _physics_process(delta: float) -> void:
	# 1. 重力运算
	if not is_on_floor():
		velocity.y -= gravity * delta

	# 2. 跳跃
	if Input.is_action_just_pressed("jump") and is_on_floor():
		velocity.y = jump_velocity

	# 3. 移动向量获取与相机朝向转换
	var input_dir: Vector2 = Input.get_vector("move_left", "move_right", "move_forward", "move_backward")
	var direction: Vector3 = (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()
	
	if direction:
		velocity.x = direction.x * speed
		velocity.z = direction.z * speed
	else:
		velocity.x = move_toward(velocity.x, 0, speed)
		velocity.z = move_toward(velocity.z, 0, speed)

	# 4. 内核级物理滑移 (自动处理碰撞与地面吸附，绝对杜绝穿模与掉出地图)
	move_and_slide()
"""

    # 6. 标准 InputMap 动作映射配置
    STANDARD_INPUT_MAP_SECTION = """[input]

move_forward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":119,"echo":false,"script":null)
]
}
move_backward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":83,"physical_keycode":0,"key_label":0,"unicode":115,"echo":false,"script":null)
]
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":65,"physical_keycode":0,"key_label":0,"unicode":97,"echo":false,"script":null)
]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":68,"physical_keycode":0,"key_label":0,"unicode":100,"echo":false,"script":null)
]
}
jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":32,"echo":false,"script":null)
]
}
fire={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":0,"position":Vector2(0, 0),"global_position":Vector2(0, 0),"factor":1.0,"button_index":1,"canceled":false,"pressed":false,"double_click":false,"script":null)
]
}
"""
